// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetHealthError, GetHealthResponse, QueryServicesData, QueryServicesError, QueryServicesResponse, GetLocationsError, GetLocationsResponse, GetOperatorsError, GetOperatorsResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Health check endpoint
 * Returns the health status of the API
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetHealthResponse, GetHealthError, ThrowOnError>({
    ...options,
    url: '/health'
}); };

/**
 * Query services with filters
 * Returns schedule information for services matching the provided filters
 */
export const queryServices = <ThrowOnError extends boolean = false>(options: Options<QueryServicesData, ThrowOnError>) => { return (options?.client ?? client).post<QueryServicesResponse, QueryServicesError, ThrowOnError>({
    ...options,
    url: '/services'
}); };

/**
 * Get all locations
 * Returns a list of all locations in the database
 */
export const getLocations = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetLocationsResponse, GetLocationsError, ThrowOnError>({
    ...options,
    url: '/locations'
}); };

/**
 * Get all operators
 * Returns a list of all train operating companies (TOCs) in the database
 */
export const getOperators = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetOperatorsResponse, GetOperatorsError, ThrowOnError>({
    ...options,
    url: '/operators'
}); };