// This file is auto-generated by @hey-api/openapi-ts

export type ServiceQueryRequest = {
    /**
     * Filter by headcode
     */
    headcode?: string;
    /**
     * Filter by operator/TOC code
     */
    operator_code?: string;
    /**
     * Filter by locations the service passes through
     */
    passes_through?: Array<{
        location_filter?: LocationFilter;
        /**
         * Earliest time at this location
         */
        time_from?: string;
        /**
         * Latest time at this location
         */
        time_to?: string;
    }>;
    /**
     * Number of services to skip (0-indexed)
     */
    offset?: number;
    /**
     * Maximum number of services to return
     */
    limit?: number;
};

export type LocationFilter = {
    /**
     * The STANOX code of the location
     */
    stanox?: string;
    /**
     * The CRS code of the location (alternative to stanox)
     */
    crs?: string;
    /**
     * The TIPLOC code of the location (alternative to stanox)
     */
    tiploc?: string;
    /**
     * The station name (alternative to stanox)
     */
    name?: string;
};

export type HealthResponse = {
    status: string;
    version: string;
};

export type ServiceQueryResponse = {
    services: Array<ServiceResponse>;
    pagination: PaginationInfo;
};

export type PaginationInfo = {
    /**
     * Number of services skipped
     */
    offset: number;
    /**
     * Maximum number of services returned
     */
    limit: number;
    /**
     * Actual number of services returned in this response
     */
    returned: number;
    /**
     * Total number of services matching the query
     */
    total_results: number;
};

export type ServiceResponse = {
    id: number;
    train_uid: string;
    signalling_id: string;
    headcode: string;
    train_category?: string;
    schedule_start_date?: string;
    schedule_end_date?: string;
    schedule_days_runs?: string;
    train_status?: string;
    /**
     * TRUST train ID (if activated)
     */
    trust_id?: string;
    /**
     * TRUST activation timestamp (if activated)
     */
    activation_time?: string;
    operator?: Operator;
    locations: Array<ScheduleLocation>;
};

export type Operator = {
    code: string;
    name: string;
};

export type Location = {
    tiploc_codes: Array<(string)>;
    stanox: string;
    crs?: string;
    full_name?: string;
};

export type ScheduleLocation = {
    id: number;
    location_type: string;
    location: Location;
    arrival?: string;
    public_arrival?: string;
    departure?: string;
    public_departure?: string;
    platform?: string;
    location_order: number;
    /**
     * Actual arrival time from TRUST feed (if available)
     */
    actual_arrival?: string;
    /**
     * Actual departure time from TRUST feed (if available)
     */
    actual_departure?: string;
    /**
     * Lateness in minutes for arrival (positive = late, negative = early)
     */
    arrival_lateness?: number;
    /**
     * Lateness in minutes for departure (positive = late, negative = early)
     */
    departure_lateness?: number;
};

export type LocationServicesResponse = {
    location: Location;
    services: Array<ServiceResponse>;
};

export type NotFoundResponse = {
    error: string;
};

export type ErrorResponse = {
    error: string;
    message: string;
    stack?: string;
};

export type GetHealthResponse = (HealthResponse);

export type GetHealthError = (ErrorResponse);

export type GetSchemaResponse = (string);

export type GetSchemaError = (ErrorResponse);

export type QueryServicesData = {
    body: ServiceQueryRequest;
};

export type QueryServicesResponse = (ServiceQueryResponse);

export type QueryServicesError = (ErrorResponse | NotFoundResponse);

export type GetLocationsResponse = (Array<Location>);

export type GetLocationsError = (ErrorResponse);

export type GetOperatorsResponse = (Array<Operator>);

export type GetOperatorsError = (ErrorResponse);

export type GetServiceData = {
    query?: {
        /**
         * Date to filter by (required when using id, optional with uid)
         */
        date?: string;
        /**
         * Schedule ID to search for (must be used with date)
         */
        id?: number;
        /**
         * Train UID to search for
         */
        uid?: string;
    };
};

export type GetServiceResponse = (ServiceResponse);

export type GetServiceError = (ErrorResponse | NotFoundResponse);