// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 

import { type Options } from "@hey-api/client-axios";
import { useMutation, UseMutationOptions, useQuery, UseQueryOptions } from "@tanstack/react-query";
import { AxiosError } from "axios";
import { getHealth, getLocations, getOperators, queryServices } from "../requests/services.gen";
import { GetHealthError, GetLocationsError, GetOperatorsError, QueryServicesData, QueryServicesError } from "../requests/types.gen";
import * as Common from "./common";
export const useGetHealth = <TData = Common.GetHealthDefaultResponse, TError = AxiosError<GetHealthError>, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseGetHealthKeyFn(clientOptions, queryKey), queryFn: () => getHealth({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetLocations = <TData = Common.GetLocationsDefaultResponse, TError = AxiosError<GetLocationsError>, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseGetLocationsKeyFn(clientOptions, queryKey), queryFn: () => getLocations({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetOperators = <TData = Common.GetOperatorsDefaultResponse, TError = AxiosError<GetOperatorsError>, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseGetOperatorsKeyFn(clientOptions, queryKey), queryFn: () => getOperators({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useQueryServices = <TData = Common.QueryServicesMutationResult, TError = AxiosError<QueryServicesError>, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<QueryServicesData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<QueryServicesData, true>, TContext>({ mutationKey: Common.UseQueryServicesKeyFn(mutationKey), mutationFn: clientOptions => queryServices(clientOptions) as unknown as Promise<TData>, ...options });
