// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 

import { type Options } from "@hey-api/client-fetch";
import { useMutation, UseMutationOptions, useQuery, UseQueryOptions } from "@tanstack/react-query";
import { getHealth, getLocations, getOperators, getSchema, getService, queryServices } from "../requests/services.gen";
import { GetHealthError, GetLocationsError, GetOperatorsError, GetSchemaError, GetServiceData, GetServiceError, QueryServicesData, QueryServicesError } from "../requests/types.gen";
import * as Common from "./common";
export const useGetHealth = <TData = Common.GetHealthDefaultResponse, TError = GetHealthError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseGetHealthKeyFn(clientOptions, queryKey), queryFn: () => getHealth({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetSchema = <TData = Common.GetSchemaDefaultResponse, TError = GetSchemaError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseGetSchemaKeyFn(clientOptions, queryKey), queryFn: () => getSchema({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetLocations = <TData = Common.GetLocationsDefaultResponse, TError = GetLocationsError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseGetLocationsKeyFn(clientOptions, queryKey), queryFn: () => getLocations({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetOperators = <TData = Common.GetOperatorsDefaultResponse, TError = GetOperatorsError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseGetOperatorsKeyFn(clientOptions, queryKey), queryFn: () => getOperators({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetService = <TData = Common.GetServiceDefaultResponse, TError = GetServiceError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetServiceData, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseGetServiceKeyFn(clientOptions, queryKey), queryFn: () => getService({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useQueryServices = <TData = Common.QueryServicesMutationResult, TError = QueryServicesError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<QueryServicesData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<QueryServicesData, true>, TContext>({ mutationKey: Common.UseQueryServicesKeyFn(mutationKey), mutationFn: clientOptions => queryServices(clientOptions) as unknown as Promise<TData>, ...options });
